// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB9bEB9uGdXWiIQgVTbv2lALAMCvHENMlI',
    appId: '1:886583770032:web:4d3b1aec87cb7c849cf475',
    messagingSenderId: '886583770032',
    projectId: 'blackcoffer-cd1a7',
    authDomain: 'blackcoffer-cd1a7.firebaseapp.com',
    storageBucket: 'blackcoffer-cd1a7.appspot.com',
    measurementId: 'G-KPNM1MDLFN',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDP88vOAH1hTbQ5JwipcWNB0FnUuk0Cb1w',
    appId: '1:886583770032:android:615174f21589fb609cf475',
    messagingSenderId: '886583770032',
    projectId: 'blackcoffer-cd1a7',
    storageBucket: 'blackcoffer-cd1a7.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAy8VtqHMDxvbsQamfBJe-2jnP034UF3N8',
    appId: '1:886583770032:ios:e727887d41aa46a39cf475',
    messagingSenderId: '886583770032',
    projectId: 'blackcoffer-cd1a7',
    storageBucket: 'blackcoffer-cd1a7.appspot.com',
    iosClientId: '886583770032-i8m1trb0q39enc6iramo6i784kbuan9k.apps.googleusercontent.com',
    iosBundleId: 'com.example.blackcoffer',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAy8VtqHMDxvbsQamfBJe-2jnP034UF3N8',
    appId: '1:886583770032:ios:fa884a66cf4d662b9cf475',
    messagingSenderId: '886583770032',
    projectId: 'blackcoffer-cd1a7',
    storageBucket: 'blackcoffer-cd1a7.appspot.com',
    iosClientId: '886583770032-ns6oo6069pd8flto2ru79b707648s5e9.apps.googleusercontent.com',
    iosBundleId: 'com.example.blackcoffer.RunnerTests',
  );
}
